{{- range .Values.serviceMeshControlPlane.namespaces }}
apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: basic-{{ . }} 
  namespace: {{ . }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "4"
spec:
  addons:
    grafana:
      enabled: true
    kiali:
      enabled: true
    prometheus:
      enabled: true
  gateways:
    openshiftRoute:
      enabled: false
  mode: MultiTenant
  policy:
    type: Istiod
  profiles:
    - default
  telemetry:
    type: Istiod
  tracing:
    sampling: 100
    type: Jaeger
  version: v2.6
{{- end }}
