apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-mesh-user-view
  namespace: {{ .Values.serviceMeshControlPlane.namespaces | first }} 
  annotations:
    argocd.argoproj.io/sync-wave: "5"
subjects:
  {{- range $group := .Values.ado_groups }}
    - kind: Group
      apiGroup: rbac.authorization.k8s.io
      name: {{ $group }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view

