{{- range $namespace := .Values.serviceMeshControlPlane.namespaces }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-mesh-user-view
  namespace: {{ $namespace }}  
  annotations:
    argocd.argoproj.io/sync-wave: "5"
subjects:
  {{- if .Values.ado_groups }}  
    {{- range $group := .Values.ado_groups }}
      - kind: Group
        apiGroup: rbac.authorization.k8s.io
        name: {{ $group }}
    {{- end }}
  {{- else }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
{{- end }}

