{{- range .Values.serviceMeshControlPlane.namespaces }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ . }}
  annotations:
    openshift.io/node-selector: ""
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    openshift.io/cluster-monitoring: "true"
{{- end }}

