# This will iterate over the namespaces defined under serviceMeshControlPlane.namespaces
{{- range $namespace := .Values.serviceMeshControlPlane.namespaces }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-mesh-user-view
  namespace: {{ $namespace }}  # Namespace from the range loop
  annotations:
    argocd.argoproj.io/sync-wave: "5"
subjects:
  {{- if .Values.ado_groups }}  # Only loop over ado_groups if it is defined and not empty
    {{- range $group := .Values.ado_groups }}
      - kind: Group
        apiGroup: rbac.authorization.k8s.io
        name: {{ $group }}
    {{- end }}
  {{- else }}
    # No groups to add
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
{{- end }}

