kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mesh-user
  namespace: {{ .Values.serviceMesh.controlPlane.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
subjects:
{{- if .Values.ado_groups }}
{{- range $group := .Values.ado_groups }}
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: {{ $group }}
{{- end }}
{{- else }}
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: default-group
{{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mesh-user

